<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Data_masyarakat extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Data_masyarakat_model');
    } 

    /*
     * Listing of data_masyarakat
     */
    function index()
    {
        $data['data_masyarakat'] = $this->Data_masyarakat_model->get_all_data_masyarakat();
        
        $data['_view'] = 'data_masyarakat/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new data_masyarakat
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
                'nik' => $this->input->post('nik'),
				'no_kk' => $this->input->post('no_kk'),
                'nama' => $this->input->post('nama'),
                'tempat_lhr' => $this->input->post('tempat_lhr'),
                'tanggal_lhr' => $this->input->post('tanggal_lhr'),
                'jenkel' => $this->input->post('jenkel'),
                'status_keluarga' => $this->input->post('status_keluarga'),
                'status_perkawinan' => $this->input->post('status_perkawinan'),
                'nama_ortu' => $this->input->post('nama_ortu'),
                'alamat' => $this->input->post('alamat'),
                'agama' => $this->input->post('agama'),
			    'pekerjaan' => $this->input->post('pekerjaan'),
            );
            
            $data_masyarakat_id = $this->Data_masyarakat_model->add_data_masyarakat($params);
            redirect('data_masyarakat/index');
        }
        else
        {            
            $data['_view'] = 'data_masyarakat/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a data_masyarakat
     */
    function edit($id_user)
    {   
        // check if the data_masyarakat exists before trying to edit it
        $data['data_masyarakat'] = $this->Data_masyarakat_model->get_data_masyarakat($id_user);
        
        if(isset($data['data_masyarakat']['id_user']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                    'nik' => $this->input->post('nik'),
                    'no_kk' => $this->input->post('no_kk'),					
					'nama' => $this->input->post('nama'),
					'tempat_lhr' => $this->input->post('tempat_lhr'),
					'tanggal_lhr' => $this->input->post('tanggal_lhr'),
					'jenkel' => $this->input->post('jenkel'),
                    'status_keluarga' => $this->input->post('status_keluarga'),
                    'status_perkawinan' => $this->input->post('status_perkawinan'),
                    'nama_ortu' => $this->input->post('nama_ortu'),
					'alamat' => $this->input->post('alamat'),
                    'agama' => $this->input->post('agama'),
                    'pekerjaan' => $this->input->post('pekerjaan'),
                );

                $this->Data_masyarakat_model->update_data_masyarakat($id_user,$params);            
                redirect('data_masyarakat/index');
            }
            else
            {
                $data['_view'] = 'data_masyarakat/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The data_masyarakat you are trying to edit does not exist.');
    } 

    /*
     * Deleting data_masyarakat
     */
    function remove($nik)
    {
        $data_masyarakat = $this->Data_masyarakat_model->get_data_masyarakat($nik);

        // check if the data_masyarakat exists before trying to delete it
        if(isset($data_masyarakat['nik']))
        {
            $this->Data_masyarakat_model->delete_data_masyarakat($nik);
            redirect('data_masyarakat/index');
        }
        else
            show_error('The data_masyarakat you are trying to delete does not exist.');
    }
    
}
