<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Data_permintaan_surat extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Data_permintaan_surat_model');
        
    } 

    /*
     * Listing of data_permintaan_surat
     */
    function index()
    {
        $data['data_permintaan_surat'] = $this->Data_permintaan_surat_model->get_all_data_permintaan_surat();
        
        $data['_view'] = 'data_permintaan_surat/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new data_permintaan_surat
     */
    function add()
    {   
        $data['nik_pembuat'] = $this->Data_permintaan_surat_model->dropdown_nik_pembuat();
        $data['keperluan'] = $this->Data_permintaan_surat_model->dropdown_keperluan();

        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'keperluan' => $this->input->post('keperluan'),
				'no_surat' => $this->input->post('no_surat'),
				'tgl_buat' => $this->input->post('tgl_buat'),
				'nik_pembuat' => $this->input->post('nik_pembuat'),
				'ket_1' => $this->input->post('ket_1'),
                'ket_2' => $this->input->post('ket_2')
            );
            
            $data_permintaan_surat_id = $this->Data_permintaan_surat_model->add_data_permintaan_surat($params);
            redirect('data_permintaan_surat/index');
        }
        else
        {            
            $data['_view'] = 'data_permintaan_surat/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a data_permintaan_surat
     */
    function edit($id_permintaan)
    {   
        $data['nik_pembuat'] = $this->Data_permintaan_surat_model->dropdown_nik_pembuat();
        $data['keperluan'] = $this->Data_permintaan_surat_model->dropdown_keperluan();

        // check if the data_permintaan_surat exists before trying to edit it
        $data['data_permintaan_surat'] = $this->Data_permintaan_surat_model->get_data_permintaan_surat($id_permintaan);
        
        if(isset($data['data_permintaan_surat']['id_permintaan']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'keperluan' => $this->input->post('keperluan'),
					'no_surat' => $this->input->post('no_surat'),
					'tgl_buat' => $this->input->post('tgl_buat'),
					'nik_pembuat' => $this->input->post('nik_pembuat'),
					'ket_1' => $this->input->post('ket_1'),
                    'ket_2' => $this->input->post('ket_2')
                );

                $this->Data_permintaan_surat_model->update_data_permintaan_surat($id_permintaan,$params);            
                redirect('data_permintaan_surat/index');
            }
            else
            {
                $data['_view'] = 'data_permintaan_surat/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The data_permintaan_surat you are trying to edit does not exist.');
    } 

    /*
     * Deleting data_permintaan_surat
     */
    function remove($id_permintaan)
    {
        $data_permintaan_surat = $this->Data_permintaan_surat_model->get_data_permintaan_surat($id_permintaan);

        // check if the data_permintaan_surat exists before trying to delete it
        if(isset($data_permintaan_surat['id_permintaan']))
        {
            $this->Data_permintaan_surat_model->delete_data_permintaan_surat($id_permintaan);
            redirect('data_permintaan_surat/index');
        }
        else
            show_error('The data_permintaan_surat you are trying to delete does not exist.');
    }

    /*
     * Print format surat
     */
    function print($id_permintaan){

        $data['masyarakat'] = $this->Data_permintaan_surat_model->get_data_masyarakat_by_nik($id_permintaan);
        $data['surat'] = $this->Data_permintaan_surat_model->get_jenis_surat($id_permintaan);

        $this->load->view('print/print_doc', $data);
    }
    
    
}
