<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Data_permintaan_surat_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get data_permintaan_surat by id_permintaan
     */
    function get_data_permintaan_surat($id_permintaan)
    {
        return $this->db->get_where('data_permintaan_surat',array('id_permintaan'=>$id_permintaan))->row_array();
    }

    function get_data_masyarakat_by_nik($id_permintaan)
    {
        $this->db->select('*');
        $this->db->from('data_masyarakat');
        $this->db->join('data_permintaan_surat', 'data_masyarakat.nik = data_permintaan_surat.nik_pembuat');
        $this->db->where('id_permintaan', $id_permintaan);
        return $this->db->get()->result_array();
    }

    function get_jenis_surat($id_permintaan)
    {
        $this->db->select('data_surat.keterangan');
        $this->db->from('data_permintaan_surat');
        $this->db->join('data_surat', 'data_permintaan_surat.keperluan = data_surat.id_surat');
        $this->db->where('id_permintaan', $id_permintaan);
        return $this->db->get()->result_array();
    }
        
    /*
     * Get all data_permintaan_surat
     */
    function get_all_data_permintaan_surat()
    {
        $this->db->order_by('id_permintaan', 'desc');
        return $this->db->get('data_permintaan_surat')->result_array();
    }
        
    /*
     * function to add new data_permintaan_surat
     */
    function add_data_permintaan_surat($params)
    {
        $this->db->insert('data_permintaan_surat',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update data_permintaan_surat
     */
    function update_data_permintaan_surat($id_permintaan,$params)
    {
        $this->db->where('id_permintaan',$id_permintaan);
        return $this->db->update('data_permintaan_surat',$params);
    }
    
    /*
     * function to delete data_permintaan_surat
     */
    function delete_data_permintaan_surat($id_permintaan)
    {
        return $this->db->delete('data_permintaan_surat',array('id_permintaan'=>$id_permintaan));
    }

    public function dropdown_nik_pembuat() {
            // Mendapatkan data ID dan nama kategori saja
            $this->db->select ('
                data_masyarakat.nik,
                data_masyarakat.nama
            ');

            $this->db->order_by('nik');

            $result = $this->db->get('data_masyarakat');
            
            $dropdown[''] = 'Pilih NIK';

            if ($result->num_rows() > 0) {
                
                foreach ($result->result_array() as $row) {
                    // Buat array berisi 'value' (id kategori) dan 'nama' (nama kategori)
                    $dropdown[$row['nik']] = $row['nik'];
                }
            }

            return $dropdown;
        }

    public function dropdown_keperluan() {
            // Mendapatkan data ID dan nama kategori saja
            $this->db->select ('
                data_surat.id_surat,
                data_surat.jenis
            ');

            $this->db->order_by('id_surat');

            $result = $this->db->get('data_surat');
            
            $dropdown[''] = 'Pilih Keperluan Surat';

            if ($result->num_rows() > 0) {
                
                foreach ($result->result_array() as $row) {
                    // Buat array berisi 'value' (id kategori) dan 'nama' (nama kategori)
                    $dropdown[$row['id_surat']] = $row['jenis'];
                }
            }

            return $dropdown;
        }
}
