<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Data_surat_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get data_surat by id_surat
     */
    function get_data_surat($id_surat)
    {
        return $this->db->get_where('data_surat',array('id_surat'=>$id_surat))->row_array();
    }
        
    /*
     * Get all data_surat
     */
    function get_all_data_surat()
    {
        $this->db->order_by('id_surat', 'desc');
        return $this->db->get('data_surat')->result_array();
    }
        
    /*
     * function to add new data_surat
     */
    function add_data_surat($params)
    {
        $this->db->insert('data_surat',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update data_surat
     */
    function update_data_surat($id_surat,$params)
    {
        $this->db->where('id_surat',$id_surat);
        return $this->db->update('data_surat',$params);
    }
    
    /*
     * function to delete data_surat
     */
    function delete_data_surat($id_surat)
    {
        return $this->db->delete('data_surat',array('id_surat'=>$id_surat));
    }

    // Function Generate Form Dropdown
    function generate_list_surat()
    {
        $this->db->select ('
            data_surat.id_surat,
            data_surat.jenis
        ');
        
        $this->db->order_by('jenis');
        $result = $this->db->get('data_surat');

        //bikin array
        $dropdown[''] = 'Pilihlah..';

        if ($result->num_rows() > 0) {
            foreach ($result->result_array() as $row) {
                //buat array isi value dan display
                $dropdown[$row['id_surat']] = $row['jenis'];
            }
        }
        return $dropdown;
    }
}
