<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Data_masyarakat_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get data_masyarakat by nik
     */
    function get_data_masyarakat($id_user)
    {
        return $this->db->get_where('data_masyarakat',array('id_user'=>$id_user))->row_array();
    }
        
    /*
     * Get all data_masyarakat
     */
    function get_all_data_masyarakat()
    {
        $this->db->order_by('id_user', 'asc');
        return $this->db->get('data_masyarakat')->result_array();
    }
        
    /*
     * function to add new data_masyarakat
     */
    function add_data_masyarakat($params)
    {
        $this->db->insert('data_masyarakat',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update data_masyarakat
     */
    function update_data_masyarakat($id_user,$params)
    {
        $this->db->where('id_user',$id_user);
        return $this->db->update('data_masyarakat',$params);
    }
    
    /*
     * function to delete data_masyarakat
     */
    function delete_data_masyarakat($id_user)
    {
        return $this->db->delete('data_masyarakat',array('id_user'=>$id_user));
    }
}
